### ISSUE TITLE
disable maintenance on unused skeleton smlKerberos

### ISSUE THREAD

**Issue by fredericJos** [Kunstmaan/skylab#49]
![screen shot 2015-03-18 at 13 44 53](https://cloud.githubusercontent.com/assets/7270372/6709628/0d8b55ce-cd7b-11e4-93ba-ba5f668b7ff1.png)

**Comment by krispypen** [comment]
this was fixed in commit d0c6b89a5c23c20af72a7026157be58568ec664c, so in next release this smlkerberos skeleton is ignored
