### ISSUE TITLE
Database user is to long

### ISSUE THREAD

**Issue by denbatte** [Kunstmaan/skylab#69]
Tried to create a project called "mastersofinnovation".
So database user was also mastersofinnovation.

During install I noticed there was a issue connection to the database.
SequelPro showed me there was no username called mastersofinnovation.
Tried to create it manually but sequelPro told me **username to long**.

Maybe skylab needs to check if username is to long and give a error of something about it.
Now skylab just keeps running as if nothing has happened without we knowing it.

**Comment by roderik** [comment]
less issues, more pull requests :)

**Comment by denbatte** [comment]
Just for reference: MySQL user names can be up to 16 characters long.
