### ISSUE TITLE
Having pgsql extension doesn't mean you have an active postgress db

### ISSUE THREAD

**Issue by kimausloos** [Kunstmaan/skylab#98]
See event 1dc30c9901d548ce848d270729177ea9, error is:
SQLSTATE[08006] [7] could not connect to server: Connection refused

https://github.com/Kunstmaan/skylab/blob/master/src/Kunstmaan/Skylab/Command/FetchCommand.php#L146

**Comment by krispypen** [comment]
same goes for mysql,

adding a check if postgres is running is not the solution. it should check if the project has postgres / mysql skeleton

so that if the project has postgres skeleton and postgres is not running, it should fail.
